"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";

const defaultServices = [
  { name: "Classic Haircut", description: "A clean, classic cut", durationMinutes: 30, priceMur: 500, depositRequiredMur: 0 },
  { name: "Skin Fade & Beard", description: "Skin fade with beard shaping", durationMinutes: 60, priceMur: 900, depositRequiredMur: 300 },
];
const defaultHours = Array.from({ length: 7 }, (_, dayOfWeek) => ({ dayOfWeek, startTime: "09:00", endTime: "18:00", isClosed: dayOfWeek === 0 }));
const dayNames = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div><p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-zinc-400">{eyebrow}</p><h2 className="mt-1.5 text-xl font-semibold tracking-[-0.03em] text-zinc-950">{title}</h2><p className="mt-1 text-sm leading-6 text-zinc-500">{description}</p></div>;
}

export default function SetupPage() {
  const router = useRouter();
  const [form, setForm] = useState({ name: "", slug: "", phone: "", address: "", district: "", juicePhone: "", juiceAccountName: "", brandColor: "#18181b" });
  const [staffName, setStaffName] = useState("");
  const [services, setServices] = useState(defaultServices);
  const [hours, setHours] = useState(defaultHours);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const generatedSlug = useMemo(() => (form.slug.trim() || form.name.trim()).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""), [form.name, form.slug]);
  function updateForm(key: keyof typeof form, value: string) { setForm((current) => ({ ...current, [key]: value })); }

  async function save() {
    setSaving(true); setError(null);
    if (!form.name.trim() || !generatedSlug || !form.phone.trim() || !form.address.trim() || !form.district.trim()) { setError("Complete the salon name, phone, booking link, address, and town / area first."); setSaving(false); return; }
    const response = await fetch("/api/v1/admin/setup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ salon: { ...form, slug: generatedSlug, juicePhone: form.juicePhone.trim() || null, juiceAccountName: form.juiceAccountName.trim() || null, depositDeadlineMinutes: 30 }, staff: [{ name: staffName || "Main barber", phone: form.phone.trim() || null, isActive: true }], services: services.map((service) => ({ ...service, isActive: true })), workingHours: hours }) });
    const json = await response.json(); setSaving(false);
    if (!response.ok) { const fieldErrors = json.details?.fieldErrors ? Object.values(json.details.fieldErrors).flat().join(" ") : ""; setError([json.error ?? "Could not save setup", fieldErrors].filter(Boolean).join(" — ")); return; }
    router.push("/admin"); router.refresh();
  }

  return <main className="min-h-screen bg-[#f5f5f7] px-4 pb-32 text-zinc-950 sm:px-6 lg:pb-10">
    <header className="mx-auto flex max-w-5xl items-center justify-between py-5 sm:py-7"><Link href="/admin/login" className="flex items-center gap-2 text-sm font-semibold text-zinc-700"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-zinc-950 text-white">✂</span>Salon OS</Link><div className="flex items-center gap-2 text-xs font-semibold text-zinc-400"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-zinc-950 text-white">1</span><span>Setup</span><span className="text-zinc-300">/</span><span>Publish</span></div></header>
    <div className="mx-auto grid max-w-5xl gap-6 lg:grid-cols-[minmax(0,1fr)_320px] lg:items-start">
      <div className="space-y-5">
        <section className="premium-rise rounded-[30px] bg-zinc-950 p-6 text-white shadow-2xl shadow-zinc-950/15 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-zinc-400">Your first impression</p><h1 className="mt-3 max-w-xl text-3xl font-semibold leading-tight tracking-[-0.05em] sm:text-4xl">Set up your salon, then let the link do the work.</h1><p className="mt-3 max-w-lg text-sm leading-6 text-zinc-400">Add the details clients need to book confidently. You can change everything later.</p><div className="mt-6 flex items-center gap-3 text-xs text-zinc-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />Takes about 3 minutes</div></section>
        <section className="premium-surface space-y-5 rounded-[28px] p-5 sm:p-7"><SectionHeading eyebrow="01 · Identity" title="Tell us about your salon" description="This is what clients will see at the top of your booking page." /><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-zinc-700 sm:col-span-2">Salon name<input value={form.name} onChange={(e) => updateForm("name", e.target.value)} placeholder="e.g. The Groom Room" className="mt-1.5 w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3.5 outline-none transition focus:border-zinc-950 focus:ring-4 focus:ring-zinc-950/10" /></label><label className="text-sm font-medium text-zinc-700">Phone<input value={form.phone} onChange={(e) => updateForm("phone", e.target.value)} placeholder="+230 5XXX XXXX" className="mt-1.5 w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3.5 outline-none transition focus:border-zinc-950 focus:ring-4 focus:ring-zinc-950/10" /></label><label className="text-sm font-medium text-zinc-700">Town / Area<input value={form.district} onChange={(e) => updateForm("district", e.target.value)} placeholder="Grand Baie" className="mt-1.5 w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3.5 outline-none transition focus:border-zinc-950 focus:ring-4 focus:ring-zinc-950/10" /></label><label className="text-sm font-medium text-zinc-700 sm:col-span-2">Address<input value={form.address} onChange={(e) => updateForm("address", e.target.value)} placeholder="Street, building or landmark" className="mt-1.5 w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3.5 outline-none transition focus:border-zinc-950 focus:ring-4 focus:ring-zinc-950/10" /></label><label className="text-sm font-medium text-zinc-700 sm:col-span-2">Booking link<input value={form.slug} onChange={(e) => updateForm("slug", e.target.value)} placeholder="the-groom-room" className="mt-1.5 w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3.5 outline-none transition focus:border-zinc-950 focus:ring-4 focus:ring-zinc-950/10" /><span className="mt-1.5 block text-xs text-zinc-400">Your link: salonos.mu/<span className="font-medium text-zinc-700">{generatedSlug || "your-salon"}</span></span></label><label className="text-sm font-medium text-zinc-700">Brand colour<div className="mt-1.5 flex items-center gap-3 rounded-2xl border border-zinc-200 bg-white p-2"><input type="color" value={form.brandColor} onChange={(e) => updateForm("brandColor", e.target.value)} className="h-10 w-12 rounded-xl border-0 bg-transparent p-0.5" /><span className="font-mono text-xs text-zinc-500">{form.brandColor}</span></div></label></div></section>
        <section className="premium-surface space-y-5 rounded-[28px] p-5 sm:p-7"><SectionHeading eyebrow="02 · People" title="Your team" description="Clients can choose a barber when more than one is available." /><label className="block text-sm font-medium text-zinc-700">Primary barber or owner<input value={staffName} onChange={(e) => setStaffName(e.target.value)} placeholder="Your name" className="mt-1.5 w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3.5 outline-none transition focus:border-zinc-950 focus:ring-4 focus:ring-zinc-950/10" /></label></section>
        <section className="premium-surface space-y-5 rounded-[28px] p-5 sm:p-7"><div><SectionHeading eyebrow="03 · Menu" title="Services" description="Start with your most-booked services. You can add more later." /><button type="button" onClick={() => setServices([...services, { name: "", description: "", durationMinutes: 30, priceMur: 0, depositRequiredMur: 0 }])} className="mt-4 rounded-full bg-indigo-50 px-4 py-2.5 text-sm font-semibold text-indigo-600 transition hover:bg-indigo-100">+ Add service</button></div><div className="space-y-3">{services.map((service, index) => <div key={index} className="rounded-2xl border border-zinc-200/80 bg-zinc-100/60 p-4"><label className="block text-xs font-semibold text-zinc-500">Service Name<input value={service.name} onChange={(e) => setServices(services.map((item, i) => i === index ? { ...item, name: e.target.value } : item))} className="mt-1.5 w-full rounded-xl border border-zinc-200 bg-white px-3 py-3 font-medium outline-none focus:border-zinc-950" /></label><input value={service.description} placeholder="Short description (optional)" onChange={(e) => setServices(services.map((item, i) => i === index ? { ...item, description: e.target.value } : item))} className="mt-3 w-full rounded-xl border border-zinc-200 bg-white px-3 py-3 text-sm outline-none focus:border-zinc-950" /><div className="mt-3 grid grid-cols-3 gap-2"><label className="text-xs font-semibold text-zinc-500">Duration<div className="mt-1.5 flex items-center rounded-xl border border-zinc-200 bg-white"><input type="number" value={service.durationMinutes} onChange={(e) => setServices(services.map((item, i) => i === index ? { ...item, durationMinutes: Number(e.target.value) } : item))} className="w-full min-w-0 rounded-xl bg-transparent px-3 py-3 outline-none" /><span className="pr-3 text-xs text-zinc-400">min</span></div></label><label className="text-xs font-semibold text-zinc-500">Price (Rs)<div className="mt-1.5 flex items-center rounded-xl border border-zinc-200 bg-white"><span className="pl-3 text-xs text-zinc-400">Rs</span><input type="number" value={service.priceMur} onChange={(e) => setServices(services.map((item, i) => i === index ? { ...item, priceMur: Number(e.target.value) } : item))} className="w-full min-w-0 rounded-xl bg-transparent px-2 py-3 outline-none" /></div></label><label className="text-xs font-semibold text-zinc-500">Deposit (Rs)<div className="mt-1.5 flex items-center rounded-xl border border-zinc-200 bg-white"><span className="pl-3 text-xs text-zinc-400">Rs</span><input type="number" value={service.depositRequiredMur} onChange={(e) => setServices(services.map((item, i) => i === index ? { ...item, depositRequiredMur: Number(e.target.value) } : item))} className="w-full min-w-0 rounded-xl bg-transparent px-2 py-3 outline-none" /></div></label></div></div>)}</div><p className="text-xs text-zinc-400">Prices and deposits are shown in Mauritian rupees.</p></section>
        <section className="premium-surface space-y-5 rounded-[28px] p-5 sm:p-7"><SectionHeading eyebrow="04 · Availability" title="Opening hours" description="Clients will only see slots inside these hours." /><div className="overflow-hidden rounded-2xl border border-zinc-200/80 bg-white">{hours.map((hour, index) => <div key={hour.dayOfWeek} className="grid grid-cols-[3.5rem_1fr_1fr_auto] items-center gap-2 border-b border-zinc-100 px-3 py-3 last:border-0 sm:grid-cols-[4rem_1fr_1fr_auto]"><span className="font-semibold text-zinc-700">{dayNames[hour.dayOfWeek]}</span><label className="flex min-w-0 items-center rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm text-zinc-700"><input type="time" value={hour.startTime} disabled={hour.isClosed} onChange={(e) => setHours(hours.map((item, i) => i === index ? { ...item, startTime: e.target.value } : item))} className="w-full bg-transparent outline-none disabled:opacity-40" /><span className="ml-2 text-zinc-300">›</span></label><label className="flex min-w-0 items-center rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm text-zinc-700"><input type="time" value={hour.endTime} disabled={hour.isClosed} onChange={(e) => setHours(hours.map((item, i) => i === index ? { ...item, endTime: e.target.value } : item))} className="w-full bg-transparent outline-none disabled:opacity-40" /><span className="ml-2 text-zinc-300">›</span></label><button type="button" aria-label={`${dayNames[hour.dayOfWeek]} ${hour.isClosed ? "closed" : "open"}`} onClick={() => setHours(hours.map((item, i) => i === index ? { ...item, isClosed: !item.isClosed } : item))} className={`relative h-7 w-12 shrink-0 rounded-full p-1 transition-colors ${hour.isClosed ? "bg-zinc-300" : "bg-emerald-500"}`}><span className={`block h-5 w-5 rounded-full bg-white shadow-sm transition-transform ${hour.isClosed ? "translate-x-0" : "translate-x-5"}`} /></button></div>)}</div><p className="text-xs text-zinc-400">Swipe or tap a time field to use your phone&apos;s native time picker.</p></section>
        <section className="premium-surface space-y-5 rounded-[28px] p-5 sm:p-7"><SectionHeading eyebrow="Optional · Payments" title="MCB Juice" description="Add your Juice details now to accept deposits from day one." /><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium text-zinc-700">Juice phone number<input value={form.juicePhone} onChange={(e) => updateForm("juicePhone", e.target.value)} placeholder="+230 5XXX XXXX" className="mt-1.5 w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3.5 outline-none focus:border-zinc-950 focus:ring-4 focus:ring-zinc-950/10" /></label><label className="text-sm font-medium text-zinc-700">Account name<input value={form.juiceAccountName} onChange={(e) => updateForm("juiceAccountName", e.target.value)} placeholder="Salon account" className="mt-1.5 w-full rounded-2xl border border-zinc-200 bg-white px-4 py-3.5 outline-none focus:border-zinc-950 focus:ring-4 focus:ring-zinc-950/10" /></label></div></section>
      </div>
      <aside className="hidden lg:block lg:sticky lg:top-6"><div className="premium-surface overflow-hidden rounded-[28px]"><div className="p-5"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-zinc-400">Live preview</p><p className="mt-2 text-lg font-semibold tracking-[-0.03em]">Your booking page</p></div><div className="mx-4 rounded-[22px] bg-zinc-950 p-4 text-white"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-2xl" style={{ backgroundColor: form.brandColor }}>✂</span><div className="min-w-0"><p className="truncate font-semibold">{form.name || "Your salon"}</p><p className="truncate text-xs text-zinc-400">{form.district || "Mauritius"}</p></div></div><div className="mt-5 rounded-2xl bg-white/10 p-3"><p className="text-xs text-zinc-400">Booking link</p><p className="mt-1 truncate text-sm font-medium">salonos.mu/{generatedSlug || "your-salon"}</p></div></div><div className="space-y-3 p-5"><div className="flex items-center gap-2 text-xs text-zinc-500"><span className="h-2 w-2 rounded-full bg-emerald-400" />Ready to publish when you are</div><button onClick={save} disabled={saving} className="min-h-12 w-full rounded-2xl bg-zinc-950 px-4 py-3 font-semibold text-white shadow-lg shadow-zinc-950/15 transition hover:bg-zinc-800 disabled:opacity-50">{saving ? "Publishing…" : "Publish booking link"}</button></div></div></aside>
    </div>
    <div className="safe-bottom fixed inset-x-0 bottom-0 z-30 border-t border-white/70 bg-white/90 p-3 shadow-[0_-14px_35px_rgba(15,23,42,0.12)] backdrop-blur-2xl lg:hidden"><div className="mx-auto flex max-w-xl items-center gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-semibold text-zinc-950">Ready to publish?</p><p className="truncate text-xs text-zinc-500">{generatedSlug ? `salonos.mu/${generatedSlug}` : "Complete your salon details"}</p></div><button onClick={save} disabled={saving} className="min-h-12 rounded-2xl bg-zinc-950 px-5 text-sm font-semibold text-white shadow-lg shadow-zinc-950/15 disabled:opacity-50">{saving ? "Saving…" : "Publish"}</button></div></div>
    {error && <div className="fixed bottom-20 left-4 right-4 z-40 mx-auto max-w-xl rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-medium text-rose-700 shadow-lg lg:bottom-5">{error}</div>}
  </main>;
}
